#!/usr/bin/env python3
"""EXP-009 — refit RANK_OFFSETS on the CURRENT model. Do they survive, or were they stale?

EXP-008: adding the SHIPPED offsets to the current model makes 2026 WORSE by 0.017 summed LL,
on every placement market, in both orderings. That contradicts the fit that shipped them
(+55.9 nats on the 2026 holdout).

THE LIKELY CAUSE IS MY OWN FIX. The offsets were fitted on shape_sims.npz, generated by
fit_shape2.py with `RU.simulate(R, field, n_sims, seed)` — DEFAULT cut_n, i.e. 65 for every
event, and no per-event cut rule, because the cut fix landed later the same day. The live model
now cuts 65/50/70/no-cut per event. So the offsets were fitted against a different probability
distribution than the one they are applied to, and the top-N tail in a no-cut 69-man playoff
field is not the tail of a 156-man field cut at 65.

Three outcomes, all actionable:
  refit HELPS on holdout   -> the mechanism is real, ship the refitted table
  refit is NULL            -> the rank bias was an artifact of the stale cut rule, REVERT
  refit HURTS              -> revert, and treat the original +55.9 nats as fitted noise

Offsets are fitted on 2023-25 ONLY and scored on 2026. 2026 is already burnt for this mechanism
(the shipped table was validated there), so this is labelled a RE-test, not a clean holdout.
"""
import datetime as dt
import hashlib
import pickle
import sys
import time

import numpy as np

import pga_ruler as RU
import pga_sim_validate as V

SIMS = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
SEED = 71
MK = ["top5", "top10", "top20", "top5_ties", "top10_ties", "top20_ties"]
ALL = ("win", "top5", "top10", "top20", "win_ties", "top5_ties", "top10_ties", "top20_ties")
EDGES = RU.RANK_EDGES
EPS = 1e-9

KEY = hashlib.sha1(("%s|%s|%s|%s" % (RU.HALF_LIFE_D, RU.K_SHRINK, RU.SIG_SHRINK,
                                     RU.MIN_ROUNDS)).encode()).hexdigest()[:12]
fits = pickle.load(open("ratings_cache_%s.pkl" % KEY, "rb"))
events = V.load_events()
first = min(e["date"] for e in events)
burn = (dt.date.fromisoformat(str(first)[:10]) + dt.timedelta(days=270)).isoformat()
usable = [e for e in events if e["date"] >= burn and e["struct"] in ("cut_R2", "no_cut")]

# CURRENT-model probabilities: correct per-event cut rule + fitted shape slope, NO rank offsets.
P, Y, RK, OFF, YEAR = [], [], [], [0], []
t0 = time.time()
for i, ev in enumerate(usable, 1):
    R = fits.get(ev["date"])
    if R is None:
        continue
    out = RU.simulate(R, ev["field"], n_sims=SIMS, seed=SEED,
                      cut_n=RU.cut_rule(ev["name"], ev["date"], n_field=len(ev["field"])),
                      shape_slope=RU.shape_slopes(ev["name"]))
    if not out:
        continue
    pos, grp, _f = V.realised(ev)
    made = set(ev.get("made_cut") or [])
    ss = set(out)
    names = list(out)
    order = sorted(range(len(names)), key=lambda j: -((out[names[j]] or {}).get("win") or 0.0))
    rank = [0] * len(names)
    for r_, j in enumerate(order, 1):
        b = 0
        for bi, e_ in enumerate(EDGES):
            if r_ >= e_:
                b = bi
        rank[j] = b
    for j, nm in enumerate(names):
        P.append([(out[nm] or {}).get(k) or 0.0 for k in MK])
        Y.append([V.y_for(k, int(k.replace("_ties", "").replace("top", "")),
                          k.endswith("_ties"), nm, pos, grp, made, ss) or 0.0 for k in MK])
        RK.append(rank[j])
    OFF.append(len(P))
    YEAR.append(int(str(ev["date"])[:4]))
    if i % 60 == 0:
        print("   %d/%d (%.1f min)" % (i, len(usable), (time.time() - t0) / 60), flush=True)

P = np.array(P); Y = np.array(Y); RK = np.array(RK)
OFF = np.array(OFF); YEAR = np.array(YEAR)
NEV = len(OFF) - 1
print("\n%d rows, %d events\n" % (len(P), NEV), flush=True)
tr = [e for e in range(NEV) if YEAR[e] < 2026]
ho = [e for e in range(NEV) if YEAR[e] >= 2026]


def rows(idx):
    return np.concatenate([np.arange(OFF[e], OFF[e + 1]) for e in idx])


def apply_off(mi, idx, off):
    out = np.zeros(len(P))
    for e in idx:
        a, b = OFF[e], OFF[e + 1]
        p = P[a:b, mi].astype(np.float64)
        lg = np.log(np.clip(p, EPS, 1 - EPS) / (1 - np.clip(p, EPS, 1 - EPS))) + off[RK[a:b]]
        tgt = float(p.sum())
        lo, hi = -40.0, 40.0
        for _ in range(60):
            c = 0.5 * (lo + hi)
            if float((1 / (1 + np.exp(-(lg + c)))).sum()) > tgt:
                hi = c
            else:
                lo = c
        out[a:b] = 1 / (1 + np.exp(-(lg + 0.5 * (lo + hi))))
    return out


def ll(mi, idx, off=None):
    r = rows(idx)
    p = apply_off(mi, idx, off)[r] if off is not None else P[r, mi].astype(np.float64)
    y = Y[r, mi].astype(np.float64)
    q = np.clip(p, EPS, 1 - EPS)
    return float(-(y * np.log(q) + (1 - y) * np.log(1 - q)).mean())


print("=" * 86)
print("REFIT on 2023-25 (current model), scored on 2026")
print("=" * 86)
print("   %-12s %-34s %10s %10s %10s" % ("market", "refitted offsets", "LL base",
                                         "LL refit", "LL shipped"))
tot_r = tot_b = tot_s = 0.0
for mi, m in enumerate(MK):
    off = np.zeros(len(EDGES))
    for _ in range(30):
        moved = False
        for bi in range(len(EDGES)):
            best, bv = off[bi], ll(mi, tr, off)
            for d in (-0.2, -0.08, -0.03, -0.01, 0.01, 0.03, 0.08, 0.2):
                t = off.copy(); t[bi] = off[bi] + d
                v = ll(mi, tr, t)
                if v < bv - 1e-9:
                    bv, best = v, t[bi]
            if abs(best - off[bi]) > 1e-12:
                off[bi] = best; moved = True
        if not moved:
            break
    ship = np.array(RU.RANK_OFFSETS[m])
    lb, lr, ls = ll(mi, ho), ll(mi, ho, off), ll(mi, ho, ship)
    tot_b += lb; tot_r += lr; tot_s += ls
    print("   %-12s %-34s %10.5f %10.5f %10.5f"
          % (m, " ".join("%+.2f" % x for x in off), lb, lr, ls))
print("\n   summed 2026 LL:  base %.5f   refit %.5f   shipped %.5f" % (tot_b, tot_r, tot_s))
print("   refit vs base   %+.6f   %s" % (tot_r - tot_b, "refit HELPS" if tot_r < tot_b else "refit HURTS"))
print("   shipped vs base %+.6f   %s" % (tot_s - tot_b, "shipped HELPS" if tot_s < tot_b else "shipped HURTS"))
